-- Add support for system messages in the messages table
-- This migration adds columns to identify and categorize system-generated messages

-- Add is_system_message column if it doesn't exist
-- System messages have sender_id = 0
ALTER TABLE messages 
ADD COLUMN IF NOT EXISTS is_system_message BOOLEAN DEFAULT FALSE 
COMMENT 'Indicates if this message was generated by the system';

-- Add system_message_type column to categorize system messages
ALTER TABLE messages 
ADD COLUMN IF NOT EXISTS system_message_type ENUM('sold', 'traded', 'general') DEFAULT NULL
COMMENT 'Type of system message: sold, traded, or general notification';

-- Create index for faster queries on system messages
CREATE INDEX IF NOT EXISTS idx_messages_system ON messages(is_system_message, conversation_id);

-- Update existing messages where sender_id = 0 to mark as system messages
UPDATE messages 
SET is_system_message = TRUE 
WHERE sender_id = 0;

-- Note: sender_id = 0 is reserved for system-generated messages
-- The system will automatically:
-- 1. Send a message when product status changes to 'sold' or 'traded'
-- 2. Include product details: name, price, category, brand, condition
-- 3. Include buyer/trader full name
-- 4. Format: "The [ProductName] (₱[Price], [Details]) was already [sold/traded] to [FullName]."

SELECT 'System message support migration completed successfully!' AS status;
