CREATE TABLE IF NOT EXISTS landing_page_visits (
    id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    visit_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_visited_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO landing_page_visits (id, visit_count, last_visited_at)
VALUES (1, 0, NULL)
ON DUPLICATE KEY UPDATE id = id;
